### PR TITLE
Layout Simplification, Admin Layout Update, add Content Warning Update Functionality

### PR DESCRIPTION
**Pull request by JamiesonRoberts**

### CODE REVIEW

**Review by silent1mezzo — CHANGES_REQUESTED** [review]
Couple of things I noticed playing around with it.

1. If you approve a story and then click `Add Content Warning` it unapproves the story.
2. If you're looking at Approved stories there's no way to remove the content warning. The button just shows `Add Content Warning` but doesn't actually do anything

**Comment by silent1mezzo** [comment]
#### 📝Changed routes:


| [**/_admin**](https://www-520zbkile-my-covid-story.vercel.app/_admin) | [**/**](https://www-520zbkile-my-covid-story.vercel.app/) |
|:-:|:-:|
|<a href="https://www-520zbkile-my-covid-story.vercel.app/_admin">Screenshot of /_admin</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/lje-9xwVXIb0KGP9lceau9yrXA_yamvCchx6hILuQueN7Te_H10bbnXi2SI7mBzyzwjggVaclHzQP3-VW-mBWA.png">(view full size)</a> |<a href="https://www-520zbkile-my-covid-story.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/kS-jgy09aeMDHXaUgLFjI-PmCBLrMy_fxTrvi9sRYFAGC2uXVRVzkSKPzwtbWBWkQpVCZaggZFQo8r39wQ3YFA.png">(view full size)</a> |



| [**/story/\[id\]**](https://www-520zbkile-my-covid-story.vercel.app/story/[id]) | [**/thanks**](https://www-520zbkile-my-covid-story.vercel.app/thanks) |
|:-:|:-:|
|<a href="https://www-520zbkile-my-covid-story.vercel.app/story/[id]">Screenshot of /story/[id]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/skHKP05_FP32fQ5mKy4XhQ3OvwRB45SQyEGkPCFX2o7xb6N3eSz5PaMhJU-2epmgc7hkr7og8SrH_fAjDYg3_g.png">(view full size)</a> |<a href="https://www-520zbkile-my-covid-story.vercel.app/thanks">Screenshot of /thanks</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/JG7RrUz0gzch44KaWUWl8Ml-y4y2sv1KZ12cQQ1deiW1U2-03-h2oifc6Pmwj7M1c4tYrWgrHro9otmu8Zpuag.png">(view full size)</a> |



And 1 other route:
- [**/api/admin/update**](https://www-520zbkile-my-covid-story.vercel.app/api/admin/update)



Commit 2af026bda55242a83087010970a9336b35a2611c (https://www-520zbkile-my-covid-story.vercel.app).

**Comment by JamiesonRoberts** [comment]
> Couple of things I noticed playing around with it.
> 
> 1. If you approve a story and then click `Add Content Warning` it unapproves the story.
> 2. If you're looking at Approved stories there's no way to remove the content warning. The button just shows `Add Content Warning` but doesn't actually do anything

This was a fantastic call out @silent1mezzo, I've updated it to use react hooks so that it feels way more dynamic and works properly!

**Comment by mwickett** [comment]
This is looking really good! The admin experience has come a long way :) 

Not sure if I'm seeing the right preview (because of the branch deploy), but I expect that when I trigger an action on a story that the view will refresh to show the new state. Currently if I add a content warning, approve or delete I don't see the change reflected on the story, and when I approved a story, I don't see it showing up on the front page. 

I will pull this down and try locally after lunch!

**Comment by mwickett** [comment]
Ok, looks like it was just a preview issue - seems to work nicely locally. I like the "dimmed" effect after an action is taken.

**Review by mwickett — APPROVED** [review]
This LGTM - @silent1mezzo has the most context on admin stuff, so I'd like to wait for his ✅ before this merges.

**Comment by JamiesonRoberts** [comment]
@silent1mezzo Thought, when a mod deletes a post should we automatically set approved to false if it was true? Same for approving and un deleting a post?

**Comment by silent1mezzo** [comment]
@JamiesonRoberts ya that's what currently happens. Because I set both of them to false and update both it only sets true to delete or approve

**Comment by silent1mezzo** [comment]
One other comment after using it. I think we should remove the `Read Full` button and just show the full text (on the to be moderated page). This makes the page a lot longer but the moderator team needs to view everything anyways. Otherwise they need to click a button for each story. For Approved/Deleted pages I think it's fine to hide the content.

**Comment by JamiesonRoberts** [comment]
@silent1mezzo great point, i've adjusted it to be as you suggested, I also figured out a simpler way for some of the hooks to work to avoid a lot of duplication on things.

**Review by silent1mezzo — APPROVED** [review]
On mobile so can't fully test but looks great!

**Comment by JamiesonRoberts** [comment]
Resolves #96

**Pull request merged**
