### PR TITLE
Fix: faq/moderation

### LINKED ISSUE #145: Update FAQ to reflect improved story moderation requirements
As part of improvements to story moderation, we are applying the following change into the FAQ section for reference.
Specifically, this adds in support resources for mental health, and provisions that a story must respect science to be allowed to be published. 

The FAQ page for the following question should therefore be updated with the following content below:

## Can anyone share a story? How do we know if they’re true?

Anyone over the age of 18 can submit their story. While our focus is currently on Ontario, we welcome stories from anyone throughout Canada.
In order to keep you safe and establish trust with visitors, the content will be moderated using the following guidelines:
1. Content must be respectful, authentic, and captures their own or another’s story
2. Respects science
3. Content isn’t defamatory or bullying anyone
4. It’s not self-promoting (i.e. sell a product/business) or encouraging illegal activity
5. It’s not racist, homophobic, sexist, ableist
6. Does not contain hate speech
7. Does not promote or encourage self-harm
8. For storytellers who wish to remain anonymous, their content does not have any personally identifiable information.
9. Stories should not have personal identifying information about other people impacted by COVID-19 without their consent
A story that does not meet these guidelines will not be shared publicly.
If you have any questions or concerns, reach out toinfo@mycovidstory.ca. For additional support or resources, please see https://211ontario.ca.

### PR DESCRIPTION
**Pull request by LuckeeDev**
Added content to faq as per @kapilharesh's request.

Closes #145.

### CODE REVIEW

**Review by silent1mezzo — CHANGES_REQUESTED** [review]
Awesome! Looks like your social icon commits for mixed in here. Can you clean this up so it's just the FAQ changes?

**Comment by LuckeeDev** [comment]
Yes I saw that in each of my PRs there's a bit of a commit mix. I'll take a look and only leave the important ones

**Comment by LuckeeDev** [comment]
Had to do a forced update, but now it should be good to go @silent1mezzo!

**Review by silent1mezzo — APPROVED** [review]
👍

**Comment by davesteinberg** [comment]
Thanks for the contribution @LuckeeDev! Sorry we let it languish for a couple of days there.

**Comment by LuckeeDev** [comment]
No worries @davesteinberg!

**Pull request merged**
