### PR TITLE
Fix: better story ssg

### LINKED ISSUE #141: SSG issues
The last three stories appear to be a 404. In order, they're:
- https://www.mycovidstory.ca/story/cko1c5rjr00000wmpc4hflovj
- https://www.mycovidstory.ca/story/cko0y7an100000uicm6no6sdi
- https://www.mycovidstory.ca/story/cko0wwoqb00000wlayrilr73u

I suspect the issue lies in the SSG strategy the website is currently using... the stories were probably added after the last build and therefore were not picked up by the static site generator. I think that moving forward we should ditch full SSG because it will also make the build times grow exponentially as the number of story grows, and we should look into [incremental static regeneration](https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration). The problem with the latter is that it requires a running Node server to statically regenerate the pages, so we should also move away from Vercel.

What do you think?

### PR DESCRIPTION
**Pull request by LuckeeDev**
### Better story SSG

This PR addresses some issues related to SSG, specifically returning a **true** 404 (see `notFound` [here](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation)) instead of statically generating an error page and returning a fallback page the first time a user hits a story which was not built at build time through `getStaticPaths()`. I tried to keep the styling of the fallback page coherent with the rest of the app and with the `404` page.

Let me know what you think!

Proposal: we could extend this PR to #126 and think about a way for statically generating and paginating the high number of stories that we have on the website.

This PR is related and closes #141.

### CODE REVIEW

**Comment by mwickett** [comment]
I'm glad to see the removal of the custom error page / 404 handling, but I'm not sure about the fallback switch from 'blocking' to 'true'. `blocking` is certainly a bit slower on the first load of an unrendered / uncached page, but it eliminates all the fallback handling logic and components. So the complexity trade-off doesn't feel worth it. What do you think?

**Comment by LuckeeDev** [comment]
In my opinion it's a fair "small complexity increase for better UX" trade, because it only adds few lines of code and gives faster feedback to the user. I also think that `fallback: 'blocking'` might be the reason behind the issue I was having in #126.

**Comment by mwickett** [comment]
Alright yeah, I'm down to give it a try. Can you clean up the conflicts here so we can get a test deploy? I'll test by manually adding a new entry to the staging DB and we'll see how it handles.

**Comment by LuckeeDev** [comment]
Sure, let me know what you think after you've tried it @mwickett!

**Pull request closed without merging**
